version: "3.0"

services:
  mongo:
    image: mongo:4.1.13
    container_name: db
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - net_A

volumes:
  mongo_data:

networks:
  net_A:
    external: false
    name: net_A
