apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab09-zad2-nginx-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: lab09-zad2-nginx-name
          image: mrybarczyk/nginx-name:1.0
          ports:
            - containerPort: 80
