apiVersion: v1
kind: Service
metadata:
  name: mikroserwis-a-service
spec:
  type: LoadBalancer
  selector:
    app: mikroserwis-a
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
